version: '2'
services:
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - '2181:2181'
    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        ports:
            - '9092:9092'
            - '9094:9094'
        environment:
            HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_CREATE_TOPICS: 'answers:8:1,student_topic:8:1,school_topic:8:1'
    consumer:
        container_name: consumer
        build:
            context: ./consumer
        depends_on:
            - kafka
    producer:
        container_name: producer
        build:
            context: ./producer
        depends_on:
            - kafka
    streams:
        container_name: streams
        build:
            context: ./streams
        ports:
            - '6666:6666'
        depends_on:
            - kafka
